type Country = {
    code: string
    slug: string
    name: {
        en: string
        ru: string
    }
}

const countries: Country[] = [
    { code: 'AD', slug: 'andorra', name: { en: 'Andorra', ru: 'Андорра' } },
    {
        code: 'AE',
        slug: 'united-arab-emirates',
        name: { en: 'United Arab Emirates', ru: 'Объединенные Арабские Эмираты' },
    },
    { code: 'AF', slug: 'afghanistan', name: { en: 'Afghanistan', ru: 'Афганистан' } },
    { code: 'AG', slug: 'antigua-and-barbuda', name: { en: 'Antigua and Barbuda', ru: 'Антигуа и Барбуда' } },
    { code: 'AI', slug: 'anguilla', name: { en: 'Anguilla', ru: 'Ангилья' } },
    { code: 'AL', slug: 'albania', name: { en: 'Albania', ru: 'Албания' } },
    { code: 'AM', slug: 'armenia', name: { en: 'Armenia', ru: 'Армения' } },
    { code: 'AO', slug: 'angola', name: { en: 'Angola', ru: 'Ангола' } },
    { code: 'AQ', slug: 'antarctica', name: { en: 'Antarctica', ru: 'Антарктида' } },
    { code: 'AR', slug: 'argentina', name: { en: 'Argentina', ru: 'Аргентина' } },
    { code: 'AS', slug: 'american-samoa', name: { en: 'American Samoa', ru: 'Американское Самоа' } },
    { code: 'AT', slug: 'austria', name: { en: 'Austria', ru: 'Австрия' } },
    { code: 'AU', slug: 'australia', name: { en: 'Australia', ru: 'Австралия' } },
    { code: 'AW', slug: 'aruba', name: { en: 'Aruba', ru: 'Аруба' } },
    { code: 'AX', slug: 'aland-islands', name: { en: 'Åland Islands', ru: 'Аландские острова' } },
    { code: 'AZ', slug: 'azerbaijan', name: { en: 'Azerbaijan', ru: 'Азербайджан' } },
    { code: 'BA', slug: 'bosnia-and-herzegovina', name: { en: 'Bosnia and Herzegovina', ru: 'Босния и Герцеговина' } },
    { code: 'BB', slug: 'barbados', name: { en: 'Barbados', ru: 'Барбадос' } },
    { code: 'BD', slug: 'bangladesh', name: { en: 'Bangladesh', ru: 'Бангладеш' } },
    { code: 'BE', slug: 'belgium', name: { en: 'Belgium', ru: 'Бельгия' } },
    { code: 'BF', slug: 'burkina-faso', name: { en: 'Burkina Faso', ru: 'Буркина-Фасо' } },
    { code: 'BG', slug: 'bulgaria', name: { en: 'Bulgaria', ru: 'Болгария' } },
    { code: 'BH', slug: 'bahrain', name: { en: 'Bahrain', ru: 'Бахрейн' } },
    { code: 'BI', slug: 'burundi', name: { en: 'Burundi', ru: 'Бурунди' } },
    { code: 'BJ', slug: 'benin', name: { en: 'Benin', ru: 'Бенин' } },
    { code: 'BL', slug: 'saint-barthelemy', name: { en: 'Saint Barthélemy', ru: 'Сен-Бартелеми' } },
    { code: 'BM', slug: 'bermuda', name: { en: 'Bermuda', ru: 'Бермуды' } },
    { code: 'BN', slug: 'brunei-darussalam', name: { en: 'Brunei Darussalam', ru: 'Бруней-Даруссалам' } },
    { code: 'BO', slug: 'bolivia', name: { en: 'Bolivia', ru: 'Боливия' } },
    { code: 'BQ', slug: 'bonaire', name: { en: 'Bonaire', ru: 'Бонайре' } },
    { code: 'BR', slug: 'brazil', name: { en: 'Brazil', ru: 'Бразилия' } },
    { code: 'BS', slug: 'bahamas', name: { en: 'Bahamas', ru: 'Багамы' } },
    { code: 'BT', slug: 'bhutan', name: { en: 'Bhutan', ru: 'Бутан' } },
    { code: 'BV', slug: 'bouvet-island', name: { en: 'Bouvet Island', ru: 'Остров Буве' } },
    { code: 'BW', slug: 'botswana', name: { en: 'Botswana', ru: 'Ботсвана' } },
    { code: 'BY', slug: 'belarus', name: { en: 'Belarus', ru: 'Беларусь' } },
    { code: 'BZ', slug: 'belize', name: { en: 'Belize', ru: 'Белиз' } },
    { code: 'CA', slug: 'canada', name: { en: 'Canada', ru: 'Канада' } },
    { code: 'CC', slug: 'cocos-islands', name: { en: 'Cocos Islands', ru: 'Кокосовые острова' } },
    {
        code: 'CD',
        slug: 'democratic-republic-of-the-congo',
        name: { en: 'Democratic Republic of the Congo', ru: 'Демократическая Республика Конго' },
    },
    {
        code: 'CF',
        slug: 'central-african-republic',
        name: { en: 'Central African Republic', ru: 'Центральноафриканская Республика' },
    },
    { code: 'CG', slug: 'congo', name: { en: 'Congo', ru: 'Конго' } },
    { code: 'CH', slug: 'switzerland', name: { en: 'Switzerland', ru: 'Швейцария' } },
    { code: 'CI', slug: 'cote-d-ivoire', name: { en: "Côte d'Ivoire", ru: 'Кот-д’Ивуар' } },
    { code: 'CK', slug: 'cook-islands', name: { en: 'Cook Islands', ru: 'Острова Кука' } },
    { code: 'CL', slug: 'chile', name: { en: 'Chile', ru: 'Чили' } },
    { code: 'CM', slug: 'cameroon', name: { en: 'Cameroon', ru: 'Камерун' } },
    { code: 'CN', slug: 'china', name: { en: 'China', ru: 'Китай' } },
    { code: 'CO', slug: 'colombia', name: { en: 'Colombia', ru: 'Колумбия' } },
    { code: 'CR', slug: 'costa-rica', name: { en: 'Costa Rica', ru: 'Коста-Рика' } },
    { code: 'CU', slug: 'cuba', name: { en: 'Cuba', ru: 'Куба' } },
    { code: 'CV', slug: 'cape-verde', name: { en: 'Cape Verde', ru: 'Кабо-Верде' } },
    { code: 'CW', slug: 'curacao', name: { en: 'Curaçao', ru: 'Кюрасао' } },
    { code: 'CX', slug: 'christmas-island', name: { en: 'Christmas Island', ru: 'Остров Рождества' } },
    { code: 'CY', slug: 'cyprus', name: { en: 'Cyprus', ru: 'Кипр' } },
    { code: 'CZ', slug: 'czech-republic', name: { en: 'Czech Republic', ru: 'Чехия' } },
    { code: 'DE', slug: 'germany', name: { en: 'Germany', ru: 'Германия' } },
    { code: 'DJ', slug: 'djibouti', name: { en: 'Djibouti', ru: 'Джибути' } },
    { code: 'DK', slug: 'denmark', name: { en: 'Denmark', ru: 'Дания' } },
    { code: 'DM', slug: 'dominica', name: { en: 'Dominica', ru: 'Доминика' } },
    { code: 'DO', slug: 'dominican-republic', name: { en: 'Dominican Republic', ru: 'Доминиканская Республика' } },
    { code: 'DZ', slug: 'algeria', name: { en: 'Algeria', ru: 'Алжир' } },
    { code: 'EC', slug: 'ecuador', name: { en: 'Ecuador', ru: 'Эквадор' } },
    { code: 'EE', slug: 'estonia', name: { en: 'Estonia', ru: 'Эстония' } },
    { code: 'EG', slug: 'egypt', name: { en: 'Egypt', ru: 'Египет' } },
    { code: 'EH', slug: 'western-sahara', name: { en: 'Western Sahara', ru: 'Западная Сахара' } },
    { code: 'ER', slug: 'eritrea', name: { en: 'Eritrea', ru: 'Эритрея' } },
    { code: 'ES', slug: 'spain', name: { en: 'Spain', ru: 'Испания' } },
    { code: 'ET', slug: 'ethiopia', name: { en: 'Ethiopia', ru: 'Эфиопия' } },
    { code: 'FI', slug: 'finland', name: { en: 'Finland', ru: 'Финляндия' } },
    { code: 'FJ', slug: 'fiji', name: { en: 'Fiji', ru: 'Фиджи' } },
    { code: 'FK', slug: 'falkland-islands', name: { en: 'Falkland Islands', ru: 'Фолклендские острова' } },
    { code: 'FM', slug: 'micronesia', name: { en: 'Micronesia', ru: 'Микронезия' } },
    { code: 'FO', slug: 'faroe-islands', name: { en: 'Faroe Islands', ru: 'Фарерские острова' } },
    { code: 'FR', slug: 'france', name: { en: 'France', ru: 'Франция' } },
    { code: 'GA', slug: 'gabon', name: { en: 'Gabon', ru: 'Габон' } },
    { code: 'GB', slug: 'united-kingdom', name: { en: 'United Kingdom', ru: 'Великобритания' } },
    { code: 'GD', slug: 'grenada', name: { en: 'Grenada', ru: 'Гренада' } },
    { code: 'GE', slug: 'georgia', name: { en: 'Georgia', ru: 'Грузия' } },
    { code: 'GF', slug: 'french-guiana', name: { en: 'French Guiana', ru: 'Французская Гвиана' } },
    { code: 'GG', slug: 'guernsey', name: { en: 'Guernsey', ru: 'Гернси' } },
    { code: 'GH', slug: 'ghana', name: { en: 'Ghana', ru: 'Гана' } },
    { code: 'GI', slug: 'gibraltar', name: { en: 'Gibraltar', ru: 'Гибралтар' } },
    { code: 'GL', slug: 'greenland', name: { en: 'Greenland', ru: 'Гренландия' } },
    { code: 'GM', slug: 'gambia', name: { en: 'Gambia', ru: 'Гамбия' } },
    { code: 'GN', slug: 'guinea', name: { en: 'Guinea', ru: 'Гвинея' } },
    { code: 'GP', slug: 'guadeloupe', name: { en: 'Guadeloupe', ru: 'Гваделупа' } },
    { code: 'GQ', slug: 'equatorial-guinea', name: { en: 'Equatorial Guinea', ru: 'Экваториальная Гвинея' } },
    { code: 'GR', slug: 'greece', name: { en: 'Greece', ru: 'Греция' } },
    {
        code: 'GS',
        slug: 'south-georgia-and-the-south-sandwich-islands',
        name: { en: 'South Georgia and the South Sandwich Islands', ru: 'Южная Георгия и Южные Сандвичевы острова' },
    },
    { code: 'GT', slug: 'guatemala', name: { en: 'Guatemala', ru: 'Гватемала' } },
    { code: 'GU', slug: 'guam', name: { en: 'Guam', ru: 'Гуам' } },
    { code: 'GW', slug: 'guinea-bissau', name: { en: 'Guinea-Bissau', ru: 'Гвинея-Бисау' } },
    { code: 'GY', slug: 'guyana', name: { en: 'Guyana', ru: 'Гайана' } },
    { code: 'HK', slug: 'hong-kong', name: { en: 'Hong Kong', ru: 'Гонконг' } },
    {
        code: 'HM',
        slug: 'heard-island-and-mcdonald-islands',
        name: { en: 'Heard Island and McDonald Islands', ru: 'Остров Херд и острова Макдональд' },
    },
    { code: 'HN', slug: 'honduras', name: { en: 'Honduras', ru: 'Гондурас' } },
    { code: 'HR', slug: 'croatia', name: { en: 'Croatia', ru: 'Хорватия' } },
    { code: 'HT', slug: 'haiti', name: { en: 'Haiti', ru: 'Гаити' } },
    { code: 'HU', slug: 'hungary', name: { en: 'Hungary', ru: 'Венгрия' } },
    { code: 'ID', slug: 'indonesia', name: { en: 'Indonesia', ru: 'Индонезия' } },
    { code: 'IE', slug: 'ireland', name: { en: 'Ireland', ru: 'Ирландия' } },
    { code: 'IL', slug: 'israel', name: { en: 'Israel', ru: 'Израиль' } },
    { code: 'IM', slug: 'isle-of-man', name: { en: 'Isle of Man', ru: 'Остров Мэн' } },
    { code: 'IN', slug: 'india', name: { en: 'India', ru: 'Индия' } },
    {
        code: 'IO',
        slug: 'british-indian-ocean-territory',
        name: { en: 'British Indian Ocean Territory', ru: 'Британская территория в Индийском океане' },
    },
    { code: 'IQ', slug: 'iraq', name: { en: 'Iraq', ru: 'Ирак' } },
    { code: 'IR', slug: 'iran', name: { en: 'Iran', ru: 'Иран' } },
    { code: 'IS', slug: 'iceland', name: { en: 'Iceland', ru: 'Исландия' } },
    { code: 'IT', slug: 'italy', name: { en: 'Italy', ru: 'Италия' } },
    { code: 'JE', slug: 'jersey', name: { en: 'Jersey', ru: 'Джерси' } },
    { code: 'JM', slug: 'jamaica', name: { en: 'Jamaica', ru: 'Ямайка' } },
    { code: 'JO', slug: 'jordan', name: { en: 'Jordan', ru: 'Иордания' } },
    { code: 'JP', slug: 'japan', name: { en: 'Japan', ru: 'Япония' } },
    { code: 'KE', slug: 'kenya', name: { en: 'Kenya', ru: 'Кения' } },
    { code: 'KG', slug: 'kyrgyzstan', name: { en: 'Kyrgyzstan', ru: 'Киргизия' } },
    { code: 'KH', slug: 'cambodia', name: { en: 'Cambodia', ru: 'Камбоджа' } },
    { code: 'KI', slug: 'kiribati', name: { en: 'Kiribati', ru: 'Кирибати' } },
    { code: 'KM', slug: 'comoros', name: { en: 'Comoros', ru: 'Коморы' } },
    { code: 'KN', slug: 'saint-kitts-and-nevis', name: { en: 'Saint Kitts and Nevis', ru: 'Сент-Китс и Невис' } },
    { code: 'KP', slug: 'north-korea', name: { en: 'North Korea', ru: 'Северная Корея' } },
    { code: 'KR', slug: 'south-korea', name: { en: 'South Korea', ru: 'Южная Корея' } },
    { code: 'KW', slug: 'kuwait', name: { en: 'Kuwait', ru: 'Кувейт' } },
    { code: 'KY', slug: 'cayman-islands', name: { en: 'Cayman Islands', ru: 'Каймановы острова' } },
    { code: 'KZ', slug: 'kazakhstan', name: { en: 'Kazakhstan', ru: 'Казахстан' } },
    { code: 'LA', slug: 'lao', name: { en: 'Lao', ru: 'Лаос' } },
    { code: 'LB', slug: 'lebanon', name: { en: 'Lebanon', ru: 'Ливан' } },
    { code: 'LC', slug: 'saint-lucia', name: { en: 'Saint Lucia', ru: 'Сент-Люсия' } },
    { code: 'LI', slug: 'liechtenstein', name: { en: 'Liechtenstein', ru: 'Лихтенштейн' } },
    { code: 'LK', slug: 'sri-lanka', name: { en: 'Sri Lanka', ru: 'Шри-Ланка' } },
    { code: 'LR', slug: 'liberia', name: { en: 'Liberia', ru: 'Либерия' } },
    { code: 'LS', slug: 'lesotho', name: { en: 'Lesotho', ru: 'Лесото' } },
    { code: 'LT', slug: 'lithuania', name: { en: 'Lithuania', ru: 'Литва' } },
    { code: 'LU', slug: 'luxembourg', name: { en: 'Luxembourg', ru: 'Люксембург' } },
    { code: 'LV', slug: 'latvia', name: { en: 'Latvia', ru: 'Латвия' } },
    { code: 'LY', slug: 'libya', name: { en: 'Libya', ru: 'Ливия' } },
    { code: 'MA', slug: 'morocco', name: { en: 'Morocco', ru: 'Марокко' } },
    { code: 'MC', slug: 'monaco', name: { en: 'Monaco', ru: 'Монако' } },
    { code: 'MD', slug: 'moldova', name: { en: 'Moldova', ru: 'Молдова' } },
    { code: 'ME', slug: 'montenegro', name: { en: 'Montenegro', ru: 'Черногория' } },
    { code: 'MF', slug: 'saint-martin', name: { en: 'Saint Martin', ru: 'Сен-Мартен' } },
    { code: 'MG', slug: 'madagascar', name: { en: 'Madagascar', ru: 'Мадагаскар' } },
    { code: 'MH', slug: 'marshall-islands', name: { en: 'Marshall Islands', ru: 'Маршалловы острова' } },
    { code: 'MK', slug: 'macedonia', name: { en: 'Macedonia', ru: 'Македония' } },
    { code: 'ML', slug: 'mali', name: { en: 'Mali', ru: 'Мали' } },
    { code: 'MM', slug: 'myanmar', name: { en: 'Myanmar', ru: 'Мьянма' } },
    { code: 'MN', slug: 'mongolia', name: { en: 'Mongolia', ru: 'Монголия' } },
    { code: 'MO', slug: 'macao', name: { en: 'Macao', ru: 'Макао' } },
    {
        code: 'MP',
        slug: 'northern-mariana-islands',
        name: { en: 'Northern Mariana Islands', ru: 'Северные Марианские острова' },
    },
    { code: 'MQ', slug: 'martinique', name: { en: 'Martinique', ru: 'Мартиника' } },
    { code: 'MR', slug: 'mauritania', name: { en: 'Mauritania', ru: 'Мавритания' } },
    { code: 'MS', slug: 'montserrat', name: { en: 'Montserrat', ru: 'Монтсеррат' } },
    { code: 'MT', slug: 'malta', name: { en: 'Malta', ru: 'Мальта' } },
    { code: 'MU', slug: 'mauritius', name: { en: 'Mauritius', ru: 'Маврикий' } },
    { code: 'MV', slug: 'maldives', name: { en: 'Maldives', ru: 'Мальдивы' } },
    { code: 'MW', slug: 'malawi', name: { en: 'Malawi', ru: 'Малави' } },
    { code: 'MX', slug: 'mexico', name: { en: 'Mexico', ru: 'Мексика' } },
    { code: 'MY', slug: 'malaysia', name: { en: 'Malaysia', ru: 'Малайзия' } },
    { code: 'MZ', slug: 'mozambique', name: { en: 'Mozambique', ru: 'Мозамбик' } },
    { code: 'NA', slug: 'namibia', name: { en: 'Namibia', ru: 'Намибия' } },
    { code: 'NC', slug: 'new-caledonia', name: { en: 'New Caledonia', ru: 'Новая Каледония' } },
    { code: 'NE', slug: 'niger', name: { en: 'Niger', ru: 'Нигер' } },
    { code: 'NF', slug: 'norfolk-island', name: { en: 'Norfolk Island', ru: 'Остров Норфолк' } },
    { code: 'NG', slug: 'nigeria', name: { en: 'Nigeria', ru: 'Нигерия' } },
    { code: 'NI', slug: 'nicaragua', name: { en: 'Nicaragua', ru: 'Никарагуа' } },
    { code: 'NL', slug: 'netherlands', name: { en: 'Netherlands', ru: 'Нидерланды' } },
    { code: 'NO', slug: 'norway', name: { en: 'Norway', ru: 'Норвегия' } },
    { code: 'NP', slug: 'nepal', name: { en: 'Nepal', ru: 'Непал' } },
    { code: 'NR', slug: 'nauru', name: { en: 'Nauru', ru: 'Науру' } },
    { code: 'NU', slug: 'niue', name: { en: 'Niue', ru: 'Ниуэ' } },
    { code: 'NZ', slug: 'new-zealand', name: { en: 'New Zealand', ru: 'Новая Зеландия' } },
    { code: 'OM', slug: 'oman', name: { en: 'Oman', ru: 'Оман' } },
    { code: 'PA', slug: 'panama', name: { en: 'Panama', ru: 'Панама' } },
    { code: 'PE', slug: 'peru', name: { en: 'Peru', ru: 'Перу' } },
    { code: 'PF', slug: 'french-polynesia', name: { en: 'French Polynesia', ru: 'Французская Полинезия' } },
    { code: 'PG', slug: 'papua-new-guinea', name: { en: 'Papua New Guinea', ru: 'Папуа — Новая Гвинея' } },
    { code: 'PH', slug: 'philippines', name: { en: 'Philippines', ru: 'Филиппины' } },
    { code: 'PK', slug: 'pakistan', name: { en: 'Pakistan', ru: 'Пакистан' } },
    { code: 'PL', slug: 'poland', name: { en: 'Poland', ru: 'Польша' } },
    {
        code: 'PM',
        slug: 'saint-pierre-and-miquelon',
        name: { en: 'Saint Pierre and Miquelon', ru: 'Сен-Пьер и Микелон' },
    },
    { code: 'PN', slug: 'pitcairn', name: { en: 'Pitcairn', ru: 'Питкэрн' } },
    { code: 'PR', slug: 'puerto-rico', name: { en: 'Puerto Rico', ru: 'Пуэрто-Рико' } },
    { code: 'PS', slug: 'palestine', name: { en: 'Palestine', ru: 'Палестина' } },
    { code: 'PT', slug: 'portugal', name: { en: 'Portugal', ru: 'Португалия' } },
    { code: 'PW', slug: 'palau', name: { en: 'Palau', ru: 'Палау' } },
    { code: 'PY', slug: 'paraguay', name: { en: 'Paraguay', ru: 'Парагвай' } },
    { code: 'QA', slug: 'qatar', name: { en: 'Qatar', ru: 'Катар' } },
    { code: 'RE', slug: 'reunion', name: { en: 'Réunion', ru: 'Реюньон' } },
    { code: 'RO', slug: 'romania', name: { en: 'Romania', ru: 'Румыния' } },
    { code: 'RS', slug: 'serbia', name: { en: 'Serbia', ru: 'Сербия' } },
    { code: 'RU', slug: 'russia', name: { en: 'Russia', ru: 'Россия' } },
    { code: 'RW', slug: 'rwanda', name: { en: 'Rwanda', ru: 'Руанда' } },
    { code: 'SA', slug: 'saudi-arabia', name: { en: 'Saudi Arabia', ru: 'Саудовская Аравия' } },
    { code: 'SB', slug: 'solomon-islands', name: { en: 'Solomon Islands', ru: 'Соломоновы острова' } },
    { code: 'SC', slug: 'seychelles', name: { en: 'Seychelles', ru: 'Сейшельские острова' } },
    { code: 'SD', slug: 'sudan', name: { en: 'Sudan', ru: 'Судан' } },
    { code: 'SE', slug: 'Sweden', name: { en: 'Sweden', ru: 'Швеция' } },
    { code: 'SG', slug: 'singapore', name: { en: 'Singapore', ru: 'Сингапур' } },
    { code: 'SH', slug: 'saint-helena', name: { en: 'Saint Helena', ru: 'Остров Святой Елены' } },
    { code: 'SI', slug: 'slovenia', name: { en: 'Slovenia', ru: 'Словения' } },
    { code: 'SJ', slug: 'svalbard-and-jan-mayen', name: { en: 'Svalbard and Jan Mayen', ru: 'Шпицберген и Ян-Майен' } },
    { code: 'SK', slug: 'slovakia', name: { en: 'Slovakia', ru: 'Словакия' } },
    { code: 'SL', slug: 'sierra-leone', name: { en: 'Sierra Leone', ru: 'Сьерра-Леоне' } },
    { code: 'SM', slug: 'san-marino', name: { en: 'San Marino', ru: 'Сан-Марино' } },
    { code: 'SN', slug: 'senegal', name: { en: 'Senegal', ru: 'Сенегал' } },
    { code: 'SO', slug: 'somalia', name: { en: 'Somalia', ru: 'Сомали' } },
    { code: 'SR', slug: 'suriname', name: { en: 'Suriname', ru: 'Суринам' } },
    { code: 'SS', slug: 'south-sudan', name: { en: 'South Sudan', ru: 'Южный Судан' } },
    { code: 'ST', slug: 'sao-tome-and-principe', name: { en: 'Sao Tome and Principe', ru: 'Сан-Томе и Принсипи' } },
    { code: 'SV', slug: 'el-salvador', name: { en: 'El Salvador', ru: 'Сальвадор' } },
    { code: 'SX', slug: 'sint-maarten', name: { en: 'Sint Maarten', ru: 'Синт-Мартен' } },
    { code: 'SY', slug: 'syria', name: { en: 'Syria', ru: 'Сирия' } },
    { code: 'SZ', slug: 'swaziland', name: { en: 'Swaziland', ru: 'Свазиленд' } },
    {
        code: 'TC',
        slug: 'turks-and-caicos-islands',
        name: { en: 'Turks and Caicos Islands', ru: 'Острова Теркс и Кайкос' },
    },
    { code: 'TD', slug: 'chad', name: { en: 'Chad', ru: 'Чад' } },
    {
        code: 'TF',
        slug: 'french-southern-territories',
        name: { en: 'French Southern Territories', ru: 'Французские Южные и Антарктические территории' },
    },
    { code: 'TG', slug: 'togo', name: { en: 'Togo', ru: 'Того' } },
    { code: 'TH', slug: 'thailand', name: { en: 'Thailand', ru: 'Таиланд' } },
    { code: 'TJ', slug: 'tajikistan', name: { en: 'Tajikistan', ru: 'Таджикистан' } },
    { code: 'TK', slug: 'tokelau', name: { en: 'Tokelau', ru: 'Токелау' } },
    { code: 'TL', slug: 'east-timor', name: { en: 'East Timor', ru: 'Восточный Тимор' } },
    { code: 'TM', slug: 'turkmenistan', name: { en: 'Turkmenistan', ru: 'Туркменистан' } },
    { code: 'TN', slug: 'tunisia', name: { en: 'Tunisia', ru: 'Тунис' } },
    { code: 'TO', slug: 'tonga', name: { en: 'Tonga', ru: 'Тонга' } },
    { code: 'TR', slug: 'turkey', name: { en: 'Turkey', ru: 'Турция' } },
    { code: 'TT', slug: 'trinidad-and-tobago', name: { en: 'Trinidad and Tobago', ru: 'Тринидад и Тобаго' } },
    { code: 'TV', slug: 'tuvalu', name: { en: 'Tuvalu', ru: 'Тувалу' } },
    { code: 'TW', slug: 'taiwan', name: { en: 'Taiwan', ru: 'Тайвань' } },
    { code: 'TZ', slug: 'tanzania', name: { en: 'Tanzania', ru: 'Танзания' } },
    { code: 'UA', slug: 'ukraine', name: { en: 'Ukraine', ru: 'Украина' } },
    { code: 'UG', slug: 'uganda', name: { en: 'Uganda', ru: 'Уганда' } },
    {
        code: 'UM',
        slug: 'united-states-minor-outlying-islands',
        name: { en: 'United States Minor Outlying Islands', ru: 'Внешние малые острова США' },
    },
    { code: 'US', slug: 'united-states', name: { en: 'United States', ru: 'США' } },
    { code: 'UY', slug: 'uruguay', name: { en: 'Uruguay', ru: 'Уругвай' } },
    { code: 'UZ', slug: 'uzbekistan', name: { en: 'Uzbekistan', ru: 'Узбекистан' } },
    { code: 'VA', slug: 'vatican', name: { en: 'Vatican', ru: 'Ватикан' } },
    {
        code: 'VC',
        slug: 'saint-vincent-and-the-grenadines',
        name: { en: 'Saint Vincent and the Grenadines', ru: 'Сент-Винсент и Гренадины' },
    },
    { code: 'VE', slug: 'venezuela', name: { en: 'Venezuela', ru: 'Венесуэла' } },
    {
        code: 'VG',
        slug: 'british-virgin-islands',
        name: { en: 'British Virgin Islands', ru: 'Британские Виргинские острова' },
    },
    {
        code: 'VI',
        slug: 'u-s-virgin-islands',
        name: { en: 'U.S. Virgin Islands', ru: 'Американские Виргинские острова' },
    },
    { code: 'VN', slug: 'vietnam', name: { en: 'Vietnam', ru: 'Вьетнам' } },
    { code: 'VU', slug: 'vanuatu', name: { en: 'Vanuatu', ru: 'Вануату' } },
    { code: 'WF', slug: 'wallis-and-futuna', name: { en: 'Wallis and Futuna', ru: 'Уоллис и Футуна' } },
    { code: 'WS', slug: 'samoa', name: { en: 'Samoa', ru: 'Самоа' } },
    { code: 'YE', slug: 'yemen', name: { en: 'Yemen', ru: 'Йемен' } },
    { code: 'YT', slug: 'mayotte', name: { en: 'Mayotte', ru: 'Майотта' } },
    { code: 'ZA', slug: 'south-africa', name: { en: 'South Africa', ru: 'Южная Африка' } },
    { code: 'ZM', slug: 'zambia', name: { en: 'Zambia', ru: 'Замбия' } },
    { code: 'ZW', slug: 'zimbabwe', name: { en: 'Zimbabwe', ru: 'Зимбабве' } },
]

export const getCountryByCode = (countryCode: Pick<Country, 'code'>['code']): Country | undefined => {
    return countries.find(country => country.code === countryCode)
}

export const getCountryBySlug = (countrySlug: Pick<Country, 'slug'>['slug']): Country | undefined => {
    return countries.find(country => country.slug === countrySlug)
}
