/**
 * Enum for predefined categories
 */
export enum Categories {
    ABANDONED = 'ABANDONED',
    ADVENTURE_ACTIVITIES = 'ADVENTURE_ACTIVITIES',
    ARCHITECTURE = 'ARCHITECTURE',
    CAMPING_SITES = 'CAMPING_SITES',
    HIKING = 'HIKING',
    HISTORICAL = 'HISTORICAL',
    LANDMARKS = 'LANDMARKS',
    MUSEUMS = 'MUSEUMS',
    NATURAL_ATTRACTIONS = 'NATURAL_ATTRACTIONS',
    OFF_ROAD = 'OFF_ROAD',
    RECREATIONAL_AREAS = 'RECREATIONAL_AREAS',
    SCENIC_VIEWS = 'SCENIC_VIEWS',
}
