// SVGR generates a React component for each SVG file

// Icons 48x48
export { default as CameraIcon48 } from '/public/images/icons/48/camera.svg'
export { default as FlagIcon48 } from '/public/images/icons/48/flag.svg'
export { default as UserRankBeginnerIcon48 } from '/public/images/icons/48/user-rank-beginner.svg'

// Icons 32x32
export { default as StarIcon32 } from '/public/images/icons/32/star.svg'

// Icons 24x24
export { default as AlertIcon24 } from '/public/images/icons/24/alert.svg'
export { default as BookmarkFillIcon24 } from '/public/images/icons/24/bookmark-fill.svg'
export { default as BookmarkIcon24 } from '/public/images/icons/24/bookmark.svg'
export { default as CloseIcon24 } from '/public/images/icons/24/close.svg'
export { default as ComplainIcon24 } from '/public/images/icons/24/complain.svg'
export { default as CopyIcon24 } from '/public/images/icons/24/copy.svg'
export { default as DeleteIcon24 } from '/public/images/icons/24/delete.svg'
export { default as EditIcon24 } from '/public/images/icons/24/edit.svg'
export { default as FacebookIcon24 } from '/public/images/icons/24/facebook.svg'
export { default as GlobeIcon24 } from '/public/images/icons/24/globe.svg'
export { default as GoogleIcon24 } from '/public/images/icons/24/google.svg'
export { default as MapIcon24 } from '/public/images/icons/24/map.svg'
export { default as MenuIcon24 } from '/public/images/icons/24/menu.svg'
export { default as PinIcon24 } from '/public/images/icons/24/pin.svg'
export { default as PinLocationIcon24 } from '/public/images/icons/24/pin-location.svg'
export { default as PointIcon24 } from '/public/images/icons/24/point.svg'
export { default as ReviewIcon24 } from '/public/images/icons/24/review.svg'
export { default as RouteIcon24 } from '/public/images/icons/24/route.svg'
export { default as SettingsIcon24 } from '/public/images/icons/24/settings.svg'
export { default as ShareIcon24 } from '/public/images/icons/24/share.svg'
export { default as SignOutIcon24 } from '/public/images/icons/24/sign-out.svg'
export { default as StarIcon24 } from '/public/images/icons/24/star.svg'
export { default as TwitterIcon24 } from '/public/images/icons/24/twitter.svg'
export { default as UserIcon24 } from '/public/images/icons/24/user.svg'

// Icon 16x16
export { default as AlertIcon16 } from '/public/images/icons/16/alert.svg'
export { default as ArrowLeftIcon16 } from '/public/images/icons/16/arrow-left.svg'
export { default as ArrowRightIcon16 } from '/public/images/icons/16/arrow-right.svg'
export { default as BookmarkFillIcon16 } from '/public/images/icons/16/bookmark-fill.svg'
export { default as BookmarkIcon16 } from '/public/images/icons/16/bookmark.svg'
export { default as ChevronBottomIcon16 } from '/public/images/icons/16/chevron-bottom.svg'
export { default as ChevronTopIcon16 } from '/public/images/icons/16/chevron-top.svg'
export { default as CloseIcon16 } from '/public/images/icons/16/close.svg'
export { default as ComplainIcon16 } from '/public/images/icons/16/complain.svg'
export { default as DeleteIcon16 } from '/public/images/icons/16/delete.svg'
export { default as EditIcon16 } from '/public/images/icons/16/edit.svg'
export { default as FolderIcon16 } from '/public/images/icons/16/folder.svg'
export { default as InfoIcon16 } from '/public/images/icons/16/info.svg'
export { default as LocationIcon16 } from '/public/images/icons/16/location.svg'
export { default as MapIcon16 } from '/public/images/icons/16/map.svg'
export { default as MinusIcon16 } from '/public/images/icons/16/minus.svg'
export { default as MoreIcon16 } from '/public/images/icons/16/more.svg'
export { default as PinIcon16 } from '/public/images/icons/16/pin.svg'
export { default as PlusIcon16 } from '/public/images/icons/16/plus.svg'
export { default as PointIcon16 } from '/public/images/icons/16/point.svg'
export { default as QuestionIcon16 } from '/public/images/icons/16/question.svg'
export { default as ReviewIcon16 } from '/public/images/icons/16/review.svg'
export { default as SearchIcon16 } from '/public/images/icons/16/search.svg'
export { default as SettingsIcon16 } from '/public/images/icons/16/settings.svg'
export { default as SignOutIcon16 } from '/public/images/icons/16/sign-out.svg'
export { default as StarIcon16 } from '/public/images/icons/16/star.svg'
export { default as VisibilityIcon16 } from '/public/images/icons/16/visibility.svg'
export { default as VisibilityOffIcon16 } from '/public/images/icons/16/visibility-off.svg'
