// Icons 24x24
export { default as BookmarkFillIcon24 } from '/public/images/icons/24/bookmark-fill.svg'
export { default as BookmarkIcon24 } from '/public/images/icons/24/bookmark.svg'
export { default as CloseIcon24 } from '/public/images/icons/24/close.svg'
export { default as ComplainIcon24 } from '/public/images/icons/24/complain.svg'
export { default as CopyIcon24 } from '/public/images/icons/24/copy.svg'
export { default as DeleteIcon24 } from '/public/images/icons/24/delete.svg'
export { default as EditIcon24 } from '/public/images/icons/24/edit.svg'
export { default as FacebookIcon24 } from '/public/images/icons/24/facebook.svg'
export { default as GlobeIcon24 } from '/public/images/icons/24/globe.svg'
export { default as GoogleIcon24 } from '/public/images/icons/24/google.svg'
export { default as MapIcon24 } from '/public/images/icons/24/map.svg'
export { default as MenuIcon24 } from '/public/images/icons/24/menu.svg'
export { default as PinIcon24 } from '/public/images/icons/24/pin.svg'
export { default as PointIcon24 } from '/public/images/icons/24/point.svg'
export { default as ReviewIcon24 } from '/public/images/icons/24/review.svg'
export { default as RouteIcon24 } from '/public/images/icons/24/route.svg'
export { default as SettingsIcon24 } from '/public/images/icons/24/settings.svg'
export { default as SignOutIcon24 } from '/public/images/icons/24/sign-out.svg'
export { default as UserIcon24 } from '/public/images/icons/24/user.svg'

// Icon 16x16
export { default as VisibilityOffIcon16 } from '/public/images/icons/16/visibility-off.svg'
export { default as VisibilityIcon16 } from '/public/images/icons/16/visibility.svg'
export { default as SignOutIcon16 } from '/public/images/icons/16/sign-out.svg'
export { default as SettingsIcon16 } from '/public/images/icons/16/settings.svg'
export { default as SearchIcon16 } from '/public/images/icons/16/search.svg'
export { default as ReviewIcon16 } from '/public/images/icons/16/review.svg'
export { default as PointIcon16 } from '/public/images/icons/16/point.svg'
export { default as PlusIcon16 } from '/public/images/icons/16/plus.svg'
export { default as PinIcon16 } from '/public/images/icons/16/pin.svg'
export { default as CloseIcon16 } from '/public/images/icons/16/close.svg'
export { default as ArrowRightIcon16 } from '/public/images/icons/16/arrow-right.svg'
export { default as ArrowLeftIcon16 } from '/public/images/icons/16/arrow-left.svg'
export { default as AlertIcon16 } from '/public/images/icons/16/alert.svg'
